trigger:
- main

variables:
  tag: ${Build.BuildId}

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool: 
          vmImage: 'ubuntu latest'
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker-azure-acr-sc'
            repository: 'customapp1'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: ${tag}


